# Generated by Django 5.1.2 on 2024-10-13 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('w', 'в ожидании'), ('p', 'в процессе'), ('c', 'завершено')], default='w', max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_to_complete', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customering', to='task.person')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executing', to='task.person')),
            ],
        ),
    ]
