# Generated by Django 5.1.2 on 2024-10-14 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('ex_content', models.TextField(blank=True, max_length=1000, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenting', to='task.person')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_commenting', to='task.task')),
            ],
        ),
    ]
